name: xc7
channels:
  - symbiflow
dependencies:
  - symbiflow::symbiflow-yosys=0.8_3925_g6bccd35a
  - symbiflow::symbiflow-yosys-plugins=1.0.0.7_0032_g104f4fc
  - symbiflow::symbiflow-vtr=8.0.0.rc2_4003_g8980e4621
  - symbiflow::prjxray-tools
  - symbiflow::prjxray-db
  - make
  - lxml
  - simplejson
  - intervaltree
  - git
  - pip
  # Packages installed from PyPI
  - pip:
    - -r file:requirements.txt
