name: xc7
channels:
  - symbiflow
  - litex-hub
dependencies:
  - symbiflow::symbiflow-yosys=0.8_6021_gd8b2d1a2=20200708_083630
  - symbiflow::symbiflow-yosys-plugins=1.0.0.7_0174_g5e6370a=20201012_171341
  - symbiflow::symbiflow-vtr=8.0.0.rc2_5097_gf1a3bcc2a=20200916_072439
  - symbiflow::prjxray-db=0.0_0239_gd87c844=20201120_180018
  - symbiflow::prjxray-tools
  - make
  - lxml
  - simplejson
  - intervaltree
  - git
  - pip
  # Packages installed from PyPI
  - pip:
    - -r file:requirements.txt
