name: eos-s3
channels:
  - conda-forge
  - quicklogic-corp
dependencies:
  - quicklogic-corp::yosys=0.6.0_0013_g2478b28
  - quicklogic-corp::yosys-plugins=0.1.0_0005_g6bbbc9b
  - quicklogic-corp::vtr=v8.0.0_rc2_4006_g36a4d4b
  - make
  - lxml
  - simplejson
  - intervaltree
  - git
  - pip
  # Packages installed from PyPI
  - pip:
    - -r file:requirements.txt
