name: eos-s3
channels:
  - litex-hub
dependencies:
  - litex-hub::yosys=0.19_10_g0098b32c6=20220706_001518_py37
  - litex-hub::symbiflow-yosys-plugins=1.0.0_7_1002_gd149693=20220706_001518
  - litex-hub::vtr-optimized=8.0.0_5664_gb7a94b90a=20220706_001518
  - make
  - lxml
  - simplejson
  - intervaltree
  - git
  - pip
  # Packages installed from PyPI
  - pip:
    - -r requirements.txt
