name: eos-s3
channels:
  - conda-forge
  - quicklogic-corp/label/ql
dependencies:
  - yosys=0.5_7972_g4045d484=20200817_053125
  - yosys-plugins=1.2.0_0009_g9ab211c=20200817_053125
  - vtr=v8.0.0_rc2_4003_g8980e4621=20200817_053125
  - make
  - lxml
  - simplejson
  - intervaltree
  - git
  - pip
  # Packages installed from PyPI
  - pip:
    - -r file:requirements.txt
